blank_issues_enabled: false
contact_links:
  - name: Security reports
    url: https://github.com/ChaseMinShrimp/Polymath-Lab/security/advisories/new
    about: Please report vulnerabilities privately.
